// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPath() {
  return window['go']['main']['App']['GetCurrentPath']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetPathSeparator() {
  return window['go']['main']['App']['GetPathSeparator']();
}

export function GetSplitPath() {
  return window['go']['main']['App']['GetSplitPath']();
}

export function OnAppReady() {
  return window['go']['main']['App']['OnAppReady']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SetCurrentPath(arg1) {
  return window['go']['main']['App']['SetCurrentPath'](arg1);
}
