// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pathobj} from '../models';

export function GetCurrentPath():Promise<string>;

export function GetFileList():Promise<Array<pathobj.PathObj>>;

export function GetPathSeparator():Promise<string>;

export function GetSplitPath():Promise<Array<string>>;

export function OnAppReady():Promise<void>;

export function SetCurrentPath(arg1:string):Promise<void>;
